### ISSUE TITLE
Connect via TCP and UDP and also multiple listeners?

### ISSUE THREAD

**Issue by MostHated** [MarkioE/SimpleNet#12]
Hello there,
    I was wondering if a client is able to connect via both TCP and UDP at the same time allowing you to determine which message types you would like to send over each connection? Also, is it possible to have multiple listeners setup on the server side for more than one port? I wanted the interconnecting servers to connect to one port and clients to connect on another and the messages get handled differently based on what port the connection came in on.

Thanks!

**Comment by markiodev** [comment]
Hey @MostHated - All of the things here should be supported already. Hopefully [this example](https://github.com/MarkioE/Networker/blob/master/Examples/Networker.Example/Program.cs) will point you in the right direction. If not, feel free to make a new repo and point me to any issues you have.
