### ISSUE TITLE
How to setup into Unity3d ?

### ISSUE THREAD

**Issue by arcadeindy** [MarkioE/SimpleNet#13]
Please.

**Comment by markiodev** [comment]
@arcadeindy I am releasing v3 soon, I would wait for that. I'll try throw together a tutorial.

Please note that this network library is not going to magically do things for you in Unity, I designed it because I wanted something barebones which I could build upon so that I could have FULL control of all the networking.

**Comment by arcadeindy** [comment]
Thank you for your reply. Now i can compiled your library to .Net 4.6 and add into unity completed. But i have new problem about ZeroFormatter in unity. Now i try to fix it. (connect and disconnect work fine)

InvalidOperationException: Type is not supported, please register ChatMessagePacket
ZeroFormatter.Formatters.ErrorFormatter`2[TTypeResolver,T].Serialize (System.Byte[]& bytes, System.Int32 offset, T value) (at <1c2cf38bb8ea407ea801af930792b503>:0)
ZeroFormatter.ZeroFormatterSerializer+CustomSerializer`1[TTypeResolver].Serialize[T] (System.Byte[]& buffer, System.Int32 offset, T obj) (at <1c2cf38bb8ea407ea801af930792b503>:0)
ZeroFormatter.ZeroFormatterSerializer+CustomSerializer`1[TTypeResolver].Serialize[T] (T obj) (at <1c2cf38bb8ea407ea801af930792b503>:0)
ZeroFormatter.ZeroFormatterSerializer.Serialize[T] (T obj) (at <1c2cf38bb8ea407ea801af930792b503>:0)
Networker.Common.PacketSerializer.Serialize[T] (T packet) (at <97b6e75c644147579d29a64d6ce6598d>:0)
Networker.Client.NetworkerClientBase.Send[T] (T packet, Networker.Common.NetworkerProtocol protocol) (at <97b6e75c644147579d29a64d6ce6598d>:0)
TestClient.Update () (at Assets/Scripts/TestClient.cs:37)

**Comment by arcadeindy** [comment]
Thank you man, Now i solved my problem already. I used zfc.exe to generate Zeroformatter file into Unity3d. Everything work fine for send and received.

**Comment by markiodev** [comment]
@arcadeindy Great! I've almost finished version 3 which is going to be more flexible and *much* _faster_!

**Comment by markiodev** [comment]
Tutorial is coming https://markeastwood.net
