### ISSUE TITLE
 Unable to resolve service for type 'Networker.Common.Abstractions.IPacketSerialiser'

### ISSUE THREAD

**Issue by Akronae** [MarkioE/SimpleNet#18]
Hi,
I'm trying to play with Networker, so I just installed this package, then I set a simple server like this
```
    public sealed class UdpServer
    {
        private readonly IServer _server;
        
        public UdpServer (int port)
        {
            _server = new ServerBuilder().UseUdp(port).RegisterPacketHandlerModule<PacketHandler>().Build();
        }

        public void Start ()
        {
            _server.Start();
            Console.WriteLine($"UdpServer running on ${_server}");
        }
    }
```

And as soon as I instanciate `UdpServer` (not even calling Start) i got this error:
<details>

> Unhandled Exception: System.InvalidOperationException: Unable to resolve service for type 'Networker.Common.Abstractions.IPacketSerialiser' while attempting to activate 'Networker.Server.ServerPacketProcessor'.
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
>    at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
>    at Networker.Server.ServerBuilder.Build()
>    at Survixel.Server.Networking.UDP.UdpServer..ctor(Int32 port) in C:\Users\alexr\Prog\C#\Survixel.Server\Survixel.Server.Networking\UDP\UdpServer.cs:line 13
>    at Survixel.Server.Core.Program.Main() in C:\Users\alexr\Prog\C#\Survixel.Server\Survixel.Server.Core\Program.cs:line 10

</details>

**Comment by Akronae** [comment]
My bad, i had to install either `Networker.Formatter.ZeroFormatter` or the protobuf one, anyway I was confused this maybe should be more explicit :)

**Comment by markiodev** [comment]
I agree and apologise for the confusion. Need to come up with a better way to handle it without forcing a default.

**Comment by markiodev** [comment]
New error message included in upcoming changes.
