### ISSUE TITLE
Use Microsoft.Extensions.Logging for Logging

### ISSUE THREAD

**Issue by davidfowl** [MarkioE/SimpleNet#20]
Networker uses its own [ILogger abstraction](https://github.com/MarkioE/Networker/blob/76615970de594b6616b9197f9573575178f9a52e/Networker/Common/Abstractions/ILogger.cs) and doesn't benefit from any of the logger ecosystem provided by Microsoft.Extensions.Logging.

**Comment by markiodev** [comment]
Thank you David, I'll take a look at adding it.

**Comment by markiodev** [comment]
This is now done, the readme reflects the change but I still need to add a Wiki page.
