### ISSUE TITLE
How to use with Unity?

### ISSUE THREAD

**Issue by Agoxandr** [MarkioE/SimpleNet#25]
I feel dumb for asking this, but building a .dll file for Unity doesn't work, because Unity says that it has errors and unloads it.

_Unloading broken assembly Assets/Plugins/Networker/Networker.dll, this assembly can cause crashes in the runtime_

**Comment by dzmitry-lahoda** [comment]
Have you put all dependencies into plugins and set .NET Standard 2.0 as target for Unity?

**Comment by Agoxandr** [comment]
I think I have, but I was lucky to find a different solution so I might as well close this issue.
